# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build, test, sign and package a WPF or Windows Forms desktop application
# built on .NET Core.
# To learn how to migrate your existing application to .NET Core,
# refer to https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework
#
# To configure this workflow:
#
# 1. Configure environment variables
# GitHub sets default environment variables for every workflow run.
# Replace the variables relative to your project in the "env" section below.
#
# 2. Signing
# Generate a signing certificate in the Windows Application
# Packaging Project or add an existing signing certificate to the project.
# Next, use PowerShell to encode the .pfx file using Base64 encoding
# by running the following Powershell script to generate the output string:
#
# $pfx_cert = Get-Content '.\SigningCertificate.pfx' -Encoding Byte
# [System.Convert]::ToBase64String($pfx_cert) | Out-File 'SigningCertificate_Encoded.txt'
#
# Open the output file, SigningCertificate_Encoded.txt, and copy the
# string inside. Then, add the string to the repo as a GitHub secret
# and name it "Base64_Encoded_Pfx."
# For more information on how to configure your signing certificate for
# this workflow, refer to https://github.com/microsoft/github-actions-for-desktop-apps#signing
#
# Finally, add the signing certificate password to the repo as a secret and name it "Pfx_Key".
# See "Build the Windows Application Packaging project" below to see how the secret is used.
#
# For more information on GitHub Actions, refer to https://github.com/features/actions
# For a complete CI/CD sample to get started with GitHub Action workflows for Desktop Applications
# refer to https://github.com/microsoft/github-actions-for-desktop-apps

name: Wix Installer Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  WIX_PATH: 'C:\Program Files (x86)\WiX Toolset v3.11\bin'
  SOLUTION_NAME: 'SystemInfoUtility.sln'
  PUBLISH_DIR: 'SystemInfoUtility\bin\Release\net6.0-windows\win-x64\publish'
  WINDOWS_SDK_PATH: 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86'
  TIMESTAMP_URL: 'http://timestamp.digicert.com'
  SIGNED_NAME: 'System Info Utility'
  MSI_FILE_NAME: 'System Info Utility x64'
  PFX_FILE: 'cert.pfx'

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: MSBuild Restore
      run: msbuild $env:SOLUTION_NAME /t:Restore /p:Configuration=$env:Configuration
      working-directory: src
      env:
        Configuration: ${{ matrix.configuration }}

    # Publish the solution
    - name: Publish
      working-directory: src\SystemInfoUtility
      run: dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=True -p:TrimMode=CopyUsed -p:PublishReadyToRun=True

    # Get the EXE Version
    - name: Get EXE Version
      working-directory: src
      run: |
        $exeVersion = (Get-Item '${{ env.PUBLISH_DIR }}\\SystemInfoUtility.exe').VersionInfo.FileVersion
        echo "FILE_VERSION=$exeVersion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
    
    # Import the PFX
    - name: Import PFX
      working-directory: src
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String('${{ secrets.CERTIFICATE }}')
        [IO.File]::WriteAllBytes('${{ env.PFX_FILE }}', $pfx_cert_byte)
        certutil -f -p '${{ secrets.CERT_PASSWORD }}' -importpfx '${{ env.PFX_FILE }}'

    # Sign Executables
    - name: Sign Executables
      working-directory: src
      run: |
        & '${{ env.WINDOWS_SDK_PATH }}\\signtool.exe' sign /sm /t '${{ env.TIMESTAMP_URL }}' /d '${{ env.SIGNED_NAME }}' /sha1 '${{ secrets.CERT_HASH }}' '${{ env.PUBLISH_DIR }}\\SystemInfoUtility.exe'

    # Harvest the published files
    - name: Wix Harvest
      working-directory: src\SystemInfoUtility.Installer
      run: "& '${{ env.WIX_PATH }}\\heat.exe' dir '..\\${{ env.PUBLISH_DIR }}'-dr APP_INSTALLDIR -ke -srd -sreg -cg ProductComponents -var var.publishDir -t Transform.xsl -gg -out Publish.wxs"

    # Compile the Wix installer files
    - name: Wix Compile
      working-directory: src\SystemInfoUtility.Installer
      run: "& '${{ env.WIX_PATH }}\\candle.exe' -dpublishDir='..\\${{ env.PUBLISH_DIR }}' *.wxs -v -out wixobj\\"

    # Create the MSI installer
    - name: Wix Link
      working-directory: src\SystemInfoUtility.Installer
      run: "& '${{ env.WIX_PATH }}\\light.exe' -ext WixUIExtension -out 'bin\\${{ env.MSI_FILE_NAME }} ${{ env.FILE_VERSION }}.msi' -v wixobj\\*.wixobj"

    # Sign the MSI Installer
    - name: Sign MSI
      working-directory: src
      run: "& '${{ env.WINDOWS_SDK_PATH }}\\signtool.exe' sign /sm /t '${{ env.TIMESTAMP_URL }}' /d '${{ env.SIGNED_NAME }}' /sha1 '${{ secrets.CERT_HASH }}' 'SystemInfoUtility.Installer\\bin\\${{ env.MSI_FILE_NAME }} ${{ env.FILE_VERSION }}.msi'"

    # Remove the PFX
    - name: Remove PFX
      working-directory: src
      run: Remove-Item '${{ env.PFX_FILE }}'

    # Upload the MSI installer as an artifact
    - name: Upload MSI Installer
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.MSI_FILE_NAME }} ${{ env.FILE_VERSION }}
        path: 'src\SystemInfoUtility.Installer\bin\${{ env.MSI_FILE_NAME }} ${{ env.FILE_VERSION }}.msi'
        if-no-files-found: error

    # Create a Release    
    - name: Create Release
      if: github.event_name == 'push'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.FILE_VERSION }}
        release_name: Release ${{ env.FILE_VERSION }}
        body: A new release for ${{ env.FILE_VERSION }}
        draft: true
        prerelease: false